version: '3.5'

services:
  api1: &api
    container_name: rinha-de-backend-app1
    image: rinha-de-backend
    build:
      context: .
      args:
        APP_STAGE: dev
    environment:
      DB_HOST: db
      REDIS_HOST: cache
    volumes:
      - ./:/opt/www
    depends_on:
      - db
      - cache
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'

  api2:
    <<: *api
    container_name: rinha-de-backend-app2

  db:
    container_name: rinha-de-backend-db
    image: mysql:8.1
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
    ports:
      - 3306:3306
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.4GB'

  cache:
    container_name: rinha-de-backend-cache
    image: redis:latest
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.5GB'

  nginx:
    image: nginx
    container_name: rinha-de-backend-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - 9999:9999
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.1GB'

networks:
  default:
    name: rinha-de-backend
